# PART : A Data preprocessing

# STEP 1: Importing the libraries


In [4]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# STEP2: Import dataset


In [5]:
dataset=pd.read_csv('Logistic Data.csv')

In [6]:
dataset

Age  Salary  Purchased Plot
0     22   22990               0
1     38   24200               0
2     29   52030               0
3     30   68970               0
4     22   91960               0
..   ...     ...             ...
395   49   49610               1
396   54   27830               1
397   53   24200               1
398   39   39930               0
399   52   43560               1

[400 rows x 3 columns]

# STEP 3: To create feature matrix(X) and dependent variable vector(Y)

In [7]:
X=dataset.iloc[:,:-1].values
Y=dataset.iloc[:,-1].values

In [8]:
X

array([[    22,  22990],
       [    38,  24200],
       [    29,  52030],
       [    30,  68970],
       [    22,  91960],
       [    30,  70180],
       [    30, 101640],
       [    35, 181500],
       [    28,  39930],
       [    38,  78650],
       [    29,  96800],
       [    29,  62920],
       [    23, 104060],
       [    35,  21780],
       [    21,  99220],
       [    32,  96800],
       [    50,  30250],
       [    48,  31460],
       [    49,  33880],
       [    51,  35090],
       [    48,  26620],
       [    50,  59290],
       [    51,  49610],
       [    48,  26620],
       [    49,  27830],
       [    50,  24200],
       [    52,  33880],
       [    50,  36300],
       [    32,  52030],
       [    34,  21780],
       [    34,  89540],
       [    30, 165770],
       [    24,  19360],
       [    31,  53240],
       [    30, 108900],
       [    38,  32670],
       [    36,  33880],
       [    33,  59290],
       [    29,  87120],
       [    30,  37510],


In [9]:
Y

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,

# STEP 4: Replacing the missing data

In [6]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')
imputer.fit(X[::])
(X[::])=imputer.transform(X[::])

# STEP 5: Encoding (Not required)

# STEP 6: Spliting the data set into training data set and testing data set

In [7]:
from sklearn.model_selection import train_test_split
Xtrain,Xtest,Ytrain,Ytest=train_test_split(X,Y,test_size=0.2,random_state=1)

In [8]:
Xtrain

array([[    32,  33880],
       [    48,  26620],
       [    49, 141570],
       [    35,  21780],
       [    25,  98010],
       [    28, 105270],
       [    51,  39930],
       [    38,  70180],
       [    50,  27830],
       [    29,  38720],
       [    35, 163350],
       [    63,  41140],
       [    55,  25410],
       [    41,  66550],
       [    28, 108900],
       [    61,  45980],
       [    52, 106480],
       [    40,  94380],
       [    38,  93170],
       [    37,  52030],
       [    23,  59290],
       [    49, 106480],
       [    34,  41140],
       [    50,  36300],
       [    38,  60500],
       [    42, 116160],
       [    36, 136730],
       [    52, 104060],
       [    48,  95590],
       [    47,  47190],
       [    44,  71390],
       [    45,  64130],
       [    38,  88330],
       [    44,  87120],
       [    30, 116160],
       [    33, 140360],
       [    44,  62920],
       [    44,  62920],
       [    23,  99220],
       [    49,  49610],


# STEP 7: Feature Scaling

In [9]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
Xtrain=sc.fit_transform(Xtrain)
Xtest=sc.fit_transform(Xtest)

# STEP B: Build classification model

# Using logiotic regression algorithm

# STEP1: Training the linear model

In [10]:
from sklearn.linear_model import LogisticRegression
LoR=LogisticRegression(random_state=0)
LoR.fit(Xtrain,Ytrain)

LogisticRegression(random_state=0)

# STEP 2: Testing the linear model

In [11]:
Yestimated=LoR.predict(Xtest)
print(np.concatenate((Yestimated.reshape(len(Yestimated),1),Ytest.reshape(len(Ytest),1)),1))

[[0 0]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [1 0]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [1 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]


In [12]:

print(precision_score(Ytest,Yestimated))from sklearn.metrics import confusion_matrix,accuracy_score,precision_score
cm= confusion_matrix(Ytest,Yestimated)
print(cm)
print(accuracy_score(Ytest,Yestimated))

[[43  5]
 [10 22]]
0.8125
0.8148148148148148


# Using KNN algorithm

In [13]:
from sklearn.neighbors import KNeighborsClassifier
KC=KNeighborsClassifier(n_neighbors=5,weights='uniform',p=2)
KC.fit(Xtrain,Ytrain)

KNeighborsClassifier()

In [14]:
Yestimated=KC.predict(Xtest)

In [15]:
from sklearn.metrics import confusion_matrix,accuracy_score,precision_score
cm= confusion_matrix(Ytest,Yestimated)
print(cm)
print(accuracy_score(Ytest,Yestimated))
print(precision_score(Ytest,Yestimated))

[[40  8]
 [ 6 26]]
0.825
0.7647058823529411
