# PART : A Data processing

# STEP 1: Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# STEP2: Import dataset

In [3]:
dataset=pd.read_csv('investment_data.csv')

In [4]:
dataset

Capital investment  Employee salary  Advertisement expenditure       City  \
0            165361.76        136897.80                  471784.10    Kolkata   
1            162610.26        151377.59                  443898.53  Bengaluru   
2            153454.07        101145.55                  407934.54    Chennai   
3            144384.97        118671.85                  383199.62    Kolkata   
4            142119.90         91391.77                  366168.42    Chennai   
5            131889.46         99814.71                  362861.36    Kolkata   
6            134628.02        147198.87                  127716.82  Bengaluru   
7            130310.69        145530.06                  323876.68    Chennai   
8            120555.08        148718.95                  311613.29    Kolkata   
9            123347.44        108679.17                  304981.62  Bengaluru   
10           101925.64        110594.11                  229160.95    Chennai   
11           100684.52         91790.61                  249744.55  Bengaluru   
12            93876.31        127320.38                  249839.44    Chennai   
13            92004.95        135495.07                  252664.93  Bengaluru   
14           119955.80        156547.42                  256512.92    Chennai   
15           114536.17        122616.84                  261776.23    Kolkata   
16            78025.67        121597.55                  264346.06  Bengaluru   
17            94669.72        145077.58                  282574.31    Kolkata   
18            91761.72        114175.79                  294919.57    Chennai   
19            86432.26        153514.11                       0.00    Kolkata   
20            76266.42        113867.30                  298664.47  Bengaluru   
21            78402.03        153773.43                  299737.29    Kolkata   
22            74007.12        122782.75                  303319.26    Chennai   
23            67545.09        105751.03                  304768.73    Chennai   
24            77056.57         99281.34                  140574.81    Kolkata   
25            64677.27        139553.16                  137962.62  Bengaluru   
26            75341.43        144135.98                  134050.07    Chennai   
27            72120.16        127864.55                  353183.81    Kolkata   
28            66064.08        182645.56                  118148.20    Chennai   
29            65618.04        153032.06                  107138.38    Kolkata   
30            62007.04        115641.28                   91131.24    Chennai   
31            61148.94        152701.92                   88218.23    Kolkata   
32            63421.42        129219.61                   46085.25  Bengaluru   
33            55506.51        103057.49                  214634.81    Chennai   
34            46438.63        157693.92                  210797.67  Bengaluru   
35            46026.58         85047.44                  205517.64    Kolkata   
36            28676.32        127056.21                  201126.82    Chennai   
37            44082.51         51283.14                  197029.42  Bengaluru   
38            20242.15         65947.93                  185265.10    Kolkata   
39            38571.07         82982.09                  174999.30  Bengaluru   
40            28766.89        118546.05                  172795.67  Bengaluru   
41            27905.48         84710.77                  164470.71    Chennai   
42            23653.49         96189.63                  148001.11  Bengaluru   
43            15518.29        127382.30                   35534.17    Kolkata   
44            22190.30        154806.14                   28334.72  Bengaluru   
45             1012.79        124153.04                    1903.93    Kolkata   
46             1328.02        115816.21                  297114.46    Chennai   
47               12.56        135426.92                       0.00  Bengaluru   
48              554.61         5174

# STEP 3: To create feature matrix(X) and dependent variable vector(Y)

In [5]:
X=dataset.iloc[:,:-1].values
Y=dataset.iloc[:,-1].values

In [6]:
X

array([[165361.76, 136897.8, 471784.1, 'Kolkata'],
       [162610.26, 151377.59, 443898.53, 'Bengaluru'],
       [153454.07, 101145.55, 407934.54, 'Chennai'],
       [144384.97, 118671.85, 383199.62, 'Kolkata'],
       [142119.9, 91391.77, 366168.42, 'Chennai'],
       [131889.46, 99814.71, 362861.36, 'Kolkata'],
       [134628.02, 147198.87, 127716.82, 'Bengaluru'],
       [130310.69, 145530.06, 323876.68, 'Chennai'],
       [120555.08, 148718.95, 311613.29, 'Kolkata'],
       [123347.44, 108679.17, 304981.62, 'Bengaluru'],
       [101925.64, 110594.11, 229160.95, 'Chennai'],
       [100684.52, 91790.61, 249744.55, 'Bengaluru'],
       [93876.31, 127320.38, 249839.44, 'Chennai'],
       [92004.95, 135495.07, 252664.93, 'Bengaluru'],
       [119955.8, 156547.42, 256512.92, 'Chennai'],
       [114536.17, 122616.84, 261776.23, 'Kolkata'],
       [78025.67, 121597.55, 264346.06, 'Bengaluru'],
       [94669.72, 145077.58, 282574.31, 'Kolkata'],
       [91761.72, 114175.79, 294919.57, 'Chen

In [7]:
Y

array([192274.39, 191804.62, 191062.95, 182914.55, 166200.5 , 157003.68,
       156135.07, 155765.16, 152224.33, 149772.52, 146134.51, 144271.96,
       141598.08, 134319.91, 132615.21, 129929.6 , 127005.49, 125382.93,
       124279.46, 122789.42, 118486.59, 111325.58, 110364.81, 108746.55,
       108564.6 , 107416.9 , 105746.1 , 105020.87, 103294.94, 101017.2 ,
        99950.15,  97496.12,  97440.4 ,  96791.48,  96725.36,  96492.07,
        90720.75,  89961.7 ,  81241.62,  81018.32,  78252.47,  77811.39,
        71511.05,  69771.54,  65212.89,  64938.64,  49503.31,  42572.29,
        35685.97,  14693.96])

# STEP 4: Encoding

# Feature Matrix using OneHotEncoding

In [10]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[3])],remainder='passthrough')
X=np.array(ct.fit_transform(X))

In [11]:
X

array([[0.0, 0.0, 1.0, 165361.76, 136897.8, 471784.1],
       [1.0, 0.0, 0.0, 162610.26, 151377.59, 443898.53],
       [0.0, 1.0, 0.0, 153454.07, 101145.55, 407934.54],
       [0.0, 0.0, 1.0, 144384.97, 118671.85, 383199.62],
       [0.0, 1.0, 0.0, 142119.9, 91391.77, 366168.42],
       [0.0, 0.0, 1.0, 131889.46, 99814.71, 362861.36],
       [1.0, 0.0, 0.0, 134628.02, 147198.87, 127716.82],
       [0.0, 1.0, 0.0, 130310.69, 145530.06, 323876.68],
       [0.0, 0.0, 1.0, 120555.08, 148718.95, 311613.29],
       [1.0, 0.0, 0.0, 123347.44, 108679.17, 304981.62],
       [0.0, 1.0, 0.0, 101925.64, 110594.11, 229160.95],
       [1.0, 0.0, 0.0, 100684.52, 91790.61, 249744.55],
       [0.0, 1.0, 0.0, 93876.31, 127320.38, 249839.44],
       [1.0, 0.0, 0.0, 92004.95, 135495.07, 252664.93],
       [0.0, 1.0, 0.0, 119955.8, 156547.42, 256512.92],
       [0.0, 0.0, 1.0, 114536.17, 122616.84, 261776.23],
       [1.0, 0.0, 0.0, 78025.67, 121597.55, 264346.06],
       [0.0, 0.0, 1.0, 94669.72, 145077.5

# STEP 5: Replacing the missing data

In [12]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')
imputer.fit(X[::])
(X[::])=imputer.transform(X[::])

In [13]:
X

array([[0.0, 0.0, 1.0, 165361.76, 136897.8, 471784.1],
       [1.0, 0.0, 0.0, 162610.26, 151377.59, 443898.53],
       [0.0, 1.0, 0.0, 153454.07, 101145.55, 407934.54],
       [0.0, 0.0, 1.0, 144384.97, 118671.85, 383199.62],
       [0.0, 1.0, 0.0, 142119.9, 91391.77, 366168.42],
       [0.0, 0.0, 1.0, 131889.46, 99814.71, 362861.36],
       [1.0, 0.0, 0.0, 134628.02, 147198.87, 127716.82],
       [0.0, 1.0, 0.0, 130310.69, 145530.06, 323876.68],
       [0.0, 0.0, 1.0, 120555.08, 148718.95, 311613.29],
       [1.0, 0.0, 0.0, 123347.44, 108679.17, 304981.62],
       [0.0, 1.0, 0.0, 101925.64, 110594.11, 229160.95],
       [1.0, 0.0, 0.0, 100684.52, 91790.61, 249744.55],
       [0.0, 1.0, 0.0, 93876.31, 127320.38, 249839.44],
       [1.0, 0.0, 0.0, 92004.95, 135495.07, 252664.93],
       [0.0, 1.0, 0.0, 119955.8, 156547.42, 256512.92],
       [0.0, 0.0, 1.0, 114536.17, 122616.84, 261776.23],
       [1.0, 0.0, 0.0, 78025.67, 121597.55, 264346.06],
       [0.0, 0.0, 1.0, 94669.72, 145077.5

# STEP 6: Spliting the data set into training data set and testing data set

In [14]:
from sklearn.model_selection import train_test_split
Xtrain,Xtest,Ytrain,Ytest=train_test_split(X,Y,test_size=0.2,random_state=1)

In [15]:
Xtrain

array([[1.0, 0.0, 0.0, 63421.42, 129219.61, 46085.25],
       [1.0, 0.0, 0.0, 38571.07, 82982.09, 174999.3],
       [0.0, 0.0, 1.0, 78402.03, 153773.43, 299737.29],
       [0.0, 1.0, 0.0, 28676.32, 127056.21, 201126.82],
       [0.0, 0.0, 1.0, 86432.26, 153514.11, 0.0],
       [1.0, 0.0, 0.0, 23653.49, 96189.63, 148001.11],
       [1.0, 0.0, 0.0, 12.56, 116983.8, 45173.06],
       [0.0, 1.0, 0.0, 75341.43, 144135.98, 134050.07],
       [0.0, 1.0, 0.0, 74007.12, 122782.75, 303319.26],
       [1.0, 0.0, 0.0, 92004.95, 135495.07, 252664.93],
       [0.0, 1.0, 0.0, 27905.48, 84710.77, 164470.71],
       [0.0, 0.0, 1.0, 94669.72, 145077.58, 282574.31],
       [0.0, 0.0, 1.0, 1012.79, 124153.04, 1903.93],
       [0.0, 0.0, 1.0, 77056.57, 99281.34, 140574.81],
       [0.0, 1.0, 0.0, 67545.09, 105751.03, 304768.73],
       [0.0, 1.0, 0.0, 142119.9, 91391.77, 366168.42],
       [0.0, 1.0, 0.0, 55506.51, 103057.49, 214634.81],
       [0.0, 1.0, 0.0, 119955.8, 156547.42, 256512.92],
       [0.0, 

# STEP 7: Feature Scaling


In [16]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
Xtrain=sc.fit_transform(Xtrain)
Xtest=sc.fit_transform(Xtest)

In [18]:
from sklearn.preprocessing import LabelEncoder
le= LabelEncoder()
Y=np.array(le.fit_transform(Y))

In [19]:
Y

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0],
      dtype=int64)

# STEP B: Build classification mode

# STEP1: Training the linear model

In [22]:
from sklearn.linear_model import LinearRegression
LR=LinearRegression()
LR.fit(Xtrain,Ytrain)

LinearRegression()

# STEP 2: Testing the linear model

In [23]:
Yestimated=LR.predict(Xtest)

In [24]:
print(Yestimated)

[126344.55166862 105526.97808436  92558.889025    88111.12138971
 182066.55820202 174922.3170342   70309.14991871 115338.00599742
  78577.37380505 111888.2623749 ]


In [25]:
print(Ytest)

[105020.87  96492.07  78252.47  81241.62 191062.95 182914.55  35685.97
 101017.2   49503.31  97496.12]


In [26]:
Yestimated.reshape(len(Yestimated),1)
Ytest.reshape(len(Ytest),1)

array([[105020.87],
       [ 96492.07],
       [ 78252.47],
       [ 81241.62],
       [191062.95],
       [182914.55],
       [ 35685.97],
       [101017.2 ],
       [ 49503.31],
       [ 97496.12]])

In [27]:
np.concatenate((Yestimated.reshape(len(Yestimated),1),Ytest.reshape(len(Ytest),1)),1)

array([[126344.55166862, 105020.87      ],
       [105526.97808436,  96492.07      ],
       [ 92558.889025  ,  78252.47      ],
       [ 88111.12138971,  81241.62      ],
       [182066.55820202, 191062.95      ],
       [174922.3170342 , 182914.55      ],
       [ 70309.14991871,  35685.97      ],
       [115338.00599742, 101017.2       ],
       [ 78577.37380505,  49503.31      ],
       [111888.2623749 ,  97496.12      ]])

# Coefficents of the regressor

In [28]:
LR.coef_

array([-1.37412292e+02,  1.44162621e+02, -3.33290025e+00,  3.35087290e+04,
       -2.42488847e+02,  3.43382663e+03])

In [29]:
LR.intercept_

114564.32074999998

In [30]:
print(LR.predict([[1.0,0.0,0.0,50661,115641,92496]]))

[1.98727372e+09]
